import { db } from '../src/config/database.js';

// Deletes data generated by synthetic smoke accounts (email prefix `smoke-`), keeping the
// accounts themselves. Run after the write-path smoke suite (see .github/workflows/smoke.yml)
// so staging doesn't accumulate junk feedback/tickets/bookings.
//
// Order matters: Feedback and Ticket both FK Booking with `onDelete: Restrict`, so a booking
// can't be deleted while its feedback/tickets exist. Delete child-first — feedback → tickets →
// bookings. (TicketMessage cascades from Ticket; all three relate to User via `user`.)

const where = { user: { email: { startsWith: 'smoke-' } } };

const feedback = await db.feedback.deleteMany({ where });
const tickets = await db.ticket.deleteMany({ where });
const bookings = await db.booking.deleteMany({ where });

console.log(
    `synthetic data cleaned — feedback: ${feedback.count}, tickets: ${tickets.count}, bookings: ${bookings.count}`
);
await db.$disconnect();
